name: PR Agent (local, no Docker)
description: Runs PR Agent using Ollama on macOS without containers

runs:
  using: "composite"
  steps:
    - name: Check Python version
      shell: bash
      run: |
        echo "Using Python from: $(which python3)"
        python3 --version
        python3 -m pip --version

    - name: Install PR Agent (user)
      shell: bash
      run: |
        python3 -m pip install --user "pr-agent[ollama]"
        echo "$HOME/Library/Python/3.10/bin" >> $GITHUB_PATH

    - name: Run PR Agent
      shell: bash
      run: |
        export CONFIG__MODEL="${{ env.CONFIG__MODEL }}"
        export OLLAMA__API_BASE="${{ env.OLLAMA__API_BASE }}"
        export GITHUB_TOKEN="${{ env.NEW_GIT_TOKEN }}"
        "$HOME/Library/Python/3.10/bin/pr-agent" --pr_url="${{ github.event.pull_request.html_url }}" review
