name: PR Agent (local, no Docker)
description: Runs PR Agent using Ollama on macOS without containers
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install PR Agent
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install "pr-agent[ollama]"

    - name: Run PR Agent
      shell: bash
      run: |
        export CONFIG__MODEL="${{ env.CONFIG__MODEL }}"
        export OLLAMA__API_BASE="${{ env.OLLAMA__API_BASE }}"
        export GITHUB_TOKEN="${{ env.NEW_GIT_TOKEN }}"
        pr-agent run
