name: PR Agent (local, no Docker)
description: Runs PR Agent using Ollama on macOS without containers

runs:
  using: "composite"
  steps:
    - name: Check Python
      shell: bash
      run: |
        echo "Using Python from: $(which python3)"
        python3 --version
        pip3 --version

    - name: Install PR Agent
      shell: bash
      run: |
        pip3 install --upgrade pip
        pip3 install "pr-agent[ollama]"

    - name: Run PR Agent
      shell: bash
      run: |
        export CONFIG__MODEL="${{ env.CONFIG__MODEL }}"
        export OLLAMA__API_BASE="${{ env.OLLAMA__API_BASE }}"
        export GITHUB_TOKEN="${{ env.GITHUB_TOKEN }}"
        pr-agent run
