name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: [self-hosted, macOS, ARM64]  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: akhioafk/ai-pr-reviewer-aqua@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ollama            # any word
        with:
          openai_base_url: "http://localhost:11434/v1"   
          openai_light_model: "deepseek-coder-v2:16b-lite-instruct-q4_K_M"       
          openai_heavy_model: "deepseek-coder-v2:16b-lite-instruct-q4_K_M"       
          debug: false
