name: Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

jobs:
  review:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - uses: actions/checkout@v4

      - uses: akhioafk/ai-pr-reviewer-aqua@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ollama
        with:
          diffOnly: true
          disable_release_notes: true
          summarize: ""
          review_simple_changes: true
          review_comment_lgtm: false
          system_message: |
            You are an expert Java test-automation reviewer. 
            Only comment on the lines in the git diff you receive.
            If you see blank lines or stray comments, tell me to remove them.
            Do not ask for additional context or diffs.
          openai_base_url: "http://localhost:11434/v1"
          openai_light_model: "deepseek-coder-v2:16b-lite-instruct-q4_K_M"
          openai_heavy_model: "deepseek-coder-v2:16b-lite-instruct-q4_K_M"
          debug: false
