name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: [self-hosted, macOS, ARM64]  
    steps:
      - uses: coderabbitai/ai-pr-reviewer@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ollama            # any word
        with:
          debug: false
          diffOnly: true
          openai_base_url: "http://localhost:11434/v1"
          openai_light_model: "deepseek-coder-v2:16b-lite-instruct-q4_K_M"
          openai_heavy_model: "deepseek-coder-v2:16b-lite-instruct-q4_K_M"
          review_simple_changes: true
          review_comment_lgtm: false
