name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

concurrency:
  group: ${{ github.repository }}-${{ github.event.number || github.head_ref || github.sha }}-${{ github.workflow }}-${{ github.event_name == 'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: [self-hosted, macOS, ARM64]  
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: AI PR Reviewer
        uses: coderabbitai/ai-pr-reviewer@1.16.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ollama
        with:
          debug: false
          openai_base_url: "http://localhost:11434/v1"
          openai_light_model: "codellama:13b-instruct"
          openai_heavy_model: "codellama:13b-instruct"
          review_simple_changes: true
          review_comment_lgtm: false
          disable_release_notes: true
