name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
  pull_request_review_comment:
    types: [created]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ github.event_name ==
    'pull_request_review_comment' && 'pr_comment' || 'pr' }}
  cancel-in-progress: ${{ github.event_name != 'pull_request_review_comment' }}

jobs:
  review:
    runs-on: [self-hosted, macOS, ARM64]  
    steps:
      - uses: akhioafk/ai-pr-reviewer-aqua@main
        env:
          GITHUB_TOKEN: ${{ secrets.PR_AGENT_PAT }}
          OPENAI_API_KEY: ollama            # any word
        with:
          debug: false
          openai_base_url: "http://localhost:11434/v1"
          openai_light_model: "codellama:13b-instruct"
          openai_heavy_model: "codellama:13b-instruct"
          review_simple_changes: false
          review_comment_lgtm: false
