name: PR Agent (Local LLM)
on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

jobs:
  review:
    runs-on: [self-hosted, macOS, ARM64]
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: qodo-ai/pr-agent@v0.30
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          CONFIG.model: "ollama/codellama:13b-instruct"
          OLLAMA__API_BASE: "http://localhost:11434"