# name: PR-Agent Review

# on:
#   pull_request_target:
#     types: [opened, synchronize, reopened]
#   issue_comment:
#     types: [created]
#   pull_request_review_comment:
#     types: [created]

# jobs:
#   pragent:
#     runs-on: [self-hosted, macOS, ARM64]

#     steps:
#       - uses: actions/checkout@v4
#         with: { fetch-depth: 0 }

#       - name: PR-Agent
#         uses: qodo-ai/pr-agent@v0.30
#         env:
#           OPENAI_KEY: ollama              
#           PR_AGENT_OLLAMA_BASE_URL: http://localhost:11434/api
#           PR_AGENT_MODEL: codellama:13b-instruct
