name: PR Agent (Local Composite)

on:
  pull_request:
    types: [opened, reopened, ready_for_review]
  issue_comment:

jobs:
  review:
    runs-on: [self-hosted, my-mac]
    steps:
      - name: Run Local PR Agent
        uses: ./.github/actions/pr-agent-local
        env:
          GITHUB_TOKEN: ${{ secrets.NEW_GIT_TOKEN }}
          CONFIG__MODEL: "ollama/codellama:13b-instruct"
          OLLAMA__API_BASE: "http://localhost:11434"
